# DEV PROFILE PROPERTIES
server.http2.enabled                                =true
server.port                                         =${PORT:8080}
server.error.include-message                        =always
spring.config.import                                =optional:file:./dev.properties
spring.devtools.restart.trigger-file                =.restartTriggerFile
spring.docker.compose.enabled                       =false
# SECURITY
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.ridivipay.com/realms/ridivi-iabs
spring.security.oauth2.resourceserver.jwk-set-uri   =https://auth.ridivipay.com/realms/ridivi-iabs/protocol/openid-connect/certs
jwt.auth.converter.principle-attribute              =preferred_username
jwt.auth.converter.resource-id                      =ridivipay-admin-api