# PRODUCTION PROFILE PROPERTIES
server.http2.enabled                                =true
server.port                                         =${PORT:8080}
server.error.include-message                        =never
spring.config.import                                =optional:file:./prod.properties
spring.devtools.restart.enabled                     =false
spring.devtools.livereload.enabled                  =false
spring.docker.compose.enabled                       =false
# SECURITY
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.ridivipay.com/realms/ridivi-aegis
spring.security.oauth2.resourceserver.jwk-set-uri   =https://auth.ridivipay.com/realms/ridivi-aegis/protocol/openid-connect/certs
jwt.auth.converter.principle-attribute              =preferred_username
jwt.auth.converter.resource-id